[package]
name = "gw2lib"
version = "2.0.2"
edition = "2021"
workspace = "../"
description = "A simple to use Gw2 API wrapper library"
repository = "https://github.com/greaka/gw2lib"
categories = ["api-bindings"]
keywords = ["api", "guild-wars-2", "gw2", "wrapper", "async"]
readme = "../README.md"
license = "MIT/Apache-2.0"

[lib]
name = "gw2lib"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.23"
fxhash = "0.2.1"
serde = "1.0.150"
thiserror = "1.0.37"
async-trait = "0.1.59"
either = "1.8.0"
futures = "0.3.25"
serde_json = "1.0.89"
static_init = "1.0.3"
urlencoding = "2.1.2"

[dependencies.tokio]
version = "1.23.0"
default-features = false
features = ["sync", "rt", "time"]

[dependencies.hyper]
version = "0.14.23"
default-features = false
features = ["runtime", "http1", "client"]

[dependencies.hyper-rustls]
version = "0.24.0"
default-features = false
features = ["http1", "native-tokio", "logging", "tls12"]

[dependencies.gw2lib-model]
version = "2.0.1"
path = "../model"

[features]
blocking = []
